#!/usr/bin/env bash
# Made by Jesus Palencia
# Licence: GPL-2
LC_ALL=C

if [[ -z $1 ]]; then
	echo "USO: github-gpg ID"
fi

git config --global commit.gpgsign true
git config --global user.signingkey $1

echo "Finalizado."

exit 0
